# Generated by Django 3.2.9 on 2021-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('5점', '5점'), ('4점', '4점'), ('3점', '3점'), ('2점', '2점'), ('1점', '1점')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
