# Generated by Django 3.2.9 on 2021-11-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_auto_20211113_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='type',
            new_name='rate',
        ),
    ]
